export const PromotionsData = {
current: [
    {
        id: 'c0',
        name: "10% Off for Local Followers",
        targeted: 125,
        start_date: new Date("Feb 2, 2020"),
        end_date: null,
        expires: new Date("Aug 1, 2020"),
        deal_details: "10% Off",
        views: 120,
        clicks: 100,
        new_customers: 23,
        total_spend: 896,
        deal_type: "%",
        deal_value: 10,
        top_list_users: true,
        top_list_user_friends: true,
        followers: true,
        first_timers: true,
        top_customers: false,
        radius: 5,
        preferred_interests: "Fine Dining, Asian"
    },
    {
        id: 'c1',
        name: "5% Off for Local Followers",
        targeted: 100,
        start_date: new Date("Jan 2, 2020"),
        end_date: null,
        expires: new Date("Aug 10, 2020"),
        deal_details: "5% Off",
        views: 90,
        clicks: 85,
        new_customers: 17,
        total_spend: 560,
        deal_type: "%",
        deal_value: 5,
        top_list_users: true,
        top_list_user_friends: true,
        followers: true,
        first_timers: true,
        top_customers: false,
        radius: 5,
        preferred_interests: "Fine Dining, Asian"
    },
    {
        id: 'c2',
        name: "6% Off for Local Followers",
        targeted: 100,
        start_date: new Date("Mar 17, 2020"),
        end_date: null,
        expires: new Date("Aug 10, 2020"),
        deal_details: "6% Off",
        views: 130,
        clicks: 118,
        new_customers: 31,
        total_spend: 1275,
        deal_type: "%",
        deal_value: 5,
        top_list_users: true,
        top_list_user_friends: true,
        followers: true,
        first_timers: true,
        top_customers: false,
        radius: 5,
        preferred_interests: "Fine Dining, Asian"
    }
],
previous: [
    {
        id: 'p0',
        name: "10% Off for Local Followers",
        targeted: 125,
        start_date: new Date("Feb 2, 2020"),
        end_date: new Date("Mar 20, 2020"),
        expires: new Date("Aug 1, 2020"),
        deal_details: "10% Off",
        views: 120,
        clicks: 100,
        new_customers: 23,
        total_spend: 896,
        deal_type: "%",
        deal_value: 10,
        top_list_users: true,
        top_list_user_friends: true,
        followers: true,
        first_timers: true,
        top_customers: false,
        radius: 5,
        preferred_interests: "Fine Dining, Asian"
    },
    {
        id: 'p1',
        name: "5% Off for Local Followers",
        targeted: 100,
        start_date: new Date("Jan 2, 2020"),
        end_date: new Date("Feb 12, 2020"),
        expires: new Date("Aug 10, 2020"),
        deal_details: "5% Off",
        views: 90,
        clicks: 85,
        new_customers: 17,
        total_spend: 560,
        deal_type: "%",
        deal_value: 5,
        top_list_users: true,
        top_list_user_friends: true,
        followers: true,
        first_timers: true,
        top_customers: false,
        radius: 5,
        preferred_interests: "Fine Dining, Asian"
    },
    {
        id: 'p2',
        name: "6% Off for Local Followers",
        targeted: 100,
        start_date: new Date("Mar 17, 2020"),
        end_date: new Date("May 15, 2020"),
        expires: new Date("Aug 10, 2020"),
        deal_details: "6% Off",
        views: 130,
        clicks: 118,
        new_customers: 31,
        total_spend: 1275,
        deal_type: "%",
        deal_value: 5,
        top_list_users: true,
        top_list_user_friends: true,
        followers: true,
        first_timers: true,
        top_customers: false,
        radius: 5,
        preferred_interests: "Fine Dining, Asian"
    }
],
// giftDeal: {
//     name: '10% Off for Friends',
//     deal_type: "%",
//     deal_value: 10,
//     friends_limit: 5,
//     total_customers: 300,
//     total_friends: 180,
//     total_used: 110,
//     gift_deal_senders: 70,
//     start_date: new Date()
// }
};